DrakeBrewer/newtonian

src/object.cpp

Added the variables of the Object class and a simple "Hello world" just to have a main() for now and to test the compiler.

Added Object class and instances for different variables

---

.gitignore
src/object.cpp

-Added constructor for all of the variables in Object class and printed some variables from an Object instance in main()
-Also updated .gitignore by adding .vscode/

made constructor in object.cpp, added .vscode/ to gitignore

---

CMakeLists.txt

Attempted to add GoogleTest functionality to our CMAKE.

Add GoogleTest

---

src/app/physics/object/object.cpp

Put all the variables into various struct and put the object into a typedef struct.

put variables and Object into structs

---

README.md

I added Markdown code blocks to the Linux documentation so I can add this to the pull request. I will remove the unnecessary comment "I (Isaac Osorio Beltran) ...." on 1/28/25. After the pull request submission date.

Add style to linux install section in README

---

src/CMakeLists.txt
src/cmake_examples/CMakeLists.txt
src/cmake_examples/test_1/CMakeLists.txt
src/cmake_examples/test_1/hello_world.cpp
src/cmake_examples/test_2/CMakeLists.txt
src/cmake_examples/test_2/read_file.cpp
src/cmake_examples/test_2/text.txt
src/cmake_examples/test_3/CMakeLists.txt
src/cmake_examples/test_3/calc.cpp
src/cmake_examples/test_3/header.hpp
src/cmake_examples/test_3/main.cpp

Added a few examples on how to use CMake

Added example CMakeLists

---

src/app/main.cpp
src/app/physics/object/object.h
src/app/physics/object/orbitalMechanics.cpp
src/app/physics/object/orbitalMechanics.h

-I edited main.cpp in (app folder) to prompt the user for what part of the physics engine they want to simulate. Right after that is a switch case which for now in the cases I put a print statement of the relevant cool cam, but you guys will add the relevant functions you make into the case. I added my coolCam header file, you'll need to add yours too. 
-In physics\object folder I changed object.cpp into a object.h file so you can include it as a header file in your cool cam and make Object instances.  DO NOT mess around with other people's structs in object.h
-In physics\object folder I added my coolCam files (orbitalMechanics.cpp and orbitalMechanics.h) and for now have it print out the default values from the Object.

Edited main.cpp in (app), added my coolcam .cpp and .h files

---

src/app/planetSim.cpp
src/app/planetSim.h

Added free fall for a sphere object on Earth. Lots of room to refactor and cleanup such as user input. Created a base object class which contains a constructor and some setters / getters to fill in various fields as well as print methods. This commit has a main file which I used to test my class / functions but feel free to comment this out / move it so that it doesn't throw compile errors.

add free fall for spheres on Earth

---

src/simulations/CMakeLists.txt
src/simulations/fluidSim/CMakeLists.txt
src/simulations/fluidSim/fluidSim.cpp
src/simulations/fluidSim/fluidSim.hpp

Created fluid dir in the simulations dir. Created a .cpp file the runs the test and a .hpp with the includes. Also updated the cmake to include the fluid dir.

Adding fluid simulation testing

---

src/app/main.cpp
src/simulations/planetSim/objects.hpp
src/simulations/planetSim/plane.hpp
src/simulations/planetSim/planetSim.cpp
src/simulations/planetSim/planets.hpp

Completed my midterm milestone issues:
1. All changes to the objects position vector(s) will be output to stdout.
2. When the user types exit or hits the exit button ( TBD), a goodbye message will appear and the simulation will end.
3.When the user selects where the want to be ( Earth or Moon ), the gravity for that simulation is set to the correct value.
- Split the planet and object classes into separate .hpp files and added new methods.
- Made a plane class which I plan on using in the future for basic collision physics. 
- Refactored handling user input a bit, still needs work: currently assumes perfect inputs.
- Free fall loop now changes the correct vectors.
- Gave planets the ability to spawn objects.
- Added planetSim to main.cpp and included the appropriate header files.

finished midterm milestone issues

---

src/simulations/planetSim/objects.hpp
src/simulations/planetSim/plane.hpp
src/simulations/planetSim/planetSim.cpp
src/simulations/planetSim/planets.hpp

Added free fall for all planets. Also added basic plane interactions for objects. Now if a plane is spawned and an object hits the plane during free fall, the free fall loop breaks as the object "hit the ground". I also revised the main file for planetSim by splitting free fall into its own function separate from setSim. This will improve readability / maintainability by keeping separate simulations in their respective functions.

add free fall for all planets + plane interaction

---

src/ui/CMakeLists.txt
src/ui/replayTable/CMakeLists.txt
src/ui/replayTable/replayTable.hpp
src/ui/replayTable/replayTableData.cpp
src/ui/replayTable/replayTableMain.cpp

Started my coolcam, the replayTable, which records the specified attributes every n ticks in a replayTable. Right now it uses a testObject and a pretty basic command line output.

feat: added replayTable, which records specified attributes

---

src/simulations/fluidSim/fluid.hpp
src/simulations/fluidSim/fluidSim.cpp
src/simulations/fluidSim/object.hpp

Added user input for what object and what fluid to simulate with.
Added the equation for the object falling, floating and velocity, acceleration and position.
Added need to do comments.

Added user input for sim and updated equations for the sim

---

src/simulations/orbitalMechanics/mainOM.cpp
src/simulations/orbitalMechanics/orbitSimulation.cpp
src/simulations/orbitalMechanics/orbitSimulation.hpp
src/simulations/orbitalMechanics/orbitalMechanics.cpp
src/simulations/orbitalMechanics/orbitalMechanics.hpp

1) My code was originally all imperative, so I did more research this week and less volume of coding to catch up on my OO knowledge and learn some more so I can transform my code as needed into OO from imperative, which I did succesfuly
2) I also added methods to update various parameters and they for now have placeholder print statements in them
3) Also restructured mainOM.cpp and orbitSimulation.cpp by putting runSimulation() into orbtiSimulation.cpp instead of mainOM.cpp because in the future when we have to merge our cool cams together, it'll be easier to merge my work with others.
So overall, not as much coding done for this PR but more so doing individual research to familiarize myself with OO again and change my code accordingly since Qt is easier to implement into an OO design.

Restructured to OO from imperative, added methods placeholders

---

src/simulations/lightSim/LightRay.cpp
src/simulations/lightSim/Medium.cpp
src/simulations/lightSim/Medium.hpp
src/simulations/lightSim/Mirror.cpp
src/simulations/lightSim/Mirror.hpp
src/simulations/lightSim/Scene.cpp
src/simulations/lightSim/Scene.hpp
src/simulations/lightSim/lightTODO.txt

Begin implementing scene. This first implementation will be time constrained as opposed to space constrained. Objects are created and destroyed using unique_ptrs. Need to finish implementing scene in order to finish implementing calculation functions. Pivoted to 2D representation for now.

Begin implementing Scene and other objects

---

src/simulations/orbitalMechanics/orbitSimulation.cpp
src/simulations/orbitalMechanics/orbitSimulation.hpp
src/simulations/orbitalMechanics/orbitalMechanics.cpp
src/simulations/orbitalMechanics/orbitalMechanics.hpp

Added functions to update parameters:
updateMoonVelocity()
updatePlanetMass()
updatePlanetMoonDistance()
and also added a function to choose between these functions in orbitSimulation.cpp

Made parameter update functions

---

src/simulations/lightSim/CMakeLists.txt
src/simulations/planetSim/CMakeLists.txt
src/simulations/planetSim/objects.hpp
src/simulations/planetSim/plane.hpp
src/simulations/planetSim/planetSim.cpp
src/simulations/planetSim/planets.hpp

Got Cmake working and I can now render a window and some basic buttons with Qt. Also fixed some general bugs with my free fall calculations.

got Cmake and Qt working + general bug fixes

---

src/simulations/collisionSim/main.cpp
src/simulations/collisionSim/rigidBody.cpp
src/simulations/collisionSim/rigidBody.hpp

Adds a sphere and cuboid class that inherit from the rigid body class and implement the shape interface.

feat: add basic shape classes

---

src/simulations/fluidSim/fluid.hpp
src/simulations/fluidSim/fluidSim.cpp
src/simulations/fluidSim/object.hpp

- Improved drag force
- Improved end case of the fluid simulation
- Added end message that says if the object was sinking or floating

Improved Fluid simulation and the equations

---

src/simulations/lightSim/CMakeLists.txt
src/simulations/orbitalMechanics/CMakeLists.txt
src/simulations/planetSim/CMakeLists.txt
src/simulations/planetSim/objects.hpp
src/simulations/planetSim/planetSim.cpp
src/simulations/planetSim/thomas_blackBoxTest.cpp
src/simulations/planetSim/thomas_integrationTest.cpp
src/simulations/planetSim/thomas_whiteBoxTest.cpp

added tests

---

src/simulations/fluidSim/CMakeLists.txt
src/simulations/fluidSim/fluid.hpp
src/simulations/fluidSim/fluidSim.cpp
src/simulations/fluidSim/fluidSim.hpp
src/simulations/fluidSim/mainFluid.cpp
src/simulations/fluidSim/object.hpp
src/simulations/fluidSim/testingSuite.cpp

- Updated CMakeList.txt
- Improved netForce function
- Split up the fluidSim.cpp to a file and a main file
- Added a testing suite

Fluids: Improved fluid functions and added testing suite

---

src/simulations/collisionSim/CMakeLists.txt
src/simulations/collisionSim/rigidBody.cpp
src/simulations/collisionSim/rigidBody.hpp
src/simulations/collisionSim/rigidBody_test.cc
src/simulations/collisionSim/test/CMakeLists.txt
src/simulations/collisionSim/test/collision_test.cpp
src/simulations/collisionSim/test/rigidBody_test.cpp
src/simulations/collisionSim/test/vector3d_test.cpp

adds unit tests to some of the classes related to collision simulation for the engine

feat: add unit tests for collision related classes

---

src/simulations/fluidSim/CMakeLists.txt
src/simulations/planetSim/CMakeLists.txt
src/simulations/planetSim/QtApp.cpp
src/simulations/planetSim/QtApp.hpp
src/simulations/planetSim/planetSim.cpp

-Made a base Qt App class which lets you generate a custom window
-Setup Qt slots and signals to handle button inputs., planetSim can now be run from the Qt App
-Refactored the old Qt code in planetSim into its own app file which represents my application for my simulation

Qt App Working

---

src/simulations/planeInteraction/CMakeLists.txt
src/simulations/planeInteraction/QtApp.cpp
src/simulations/planeInteraction/QtApp.hpp

updated my cmakelists and created QtApp files

Cmake and Qt

---

src/simulations/planeInteraction/QtApp.cpp
src/simulations/planeInteraction/QtApp.hpp

Updated hpp and cpp QT files and setting up for user input.

Did some more QT and arranged file setup

---

src/simulations/orbitalMechanics/CMakeLists.txt
src/simulations/orbitalMechanics/MainWindow.cpp
src/simulations/orbitalMechanics/MainWindow.hpp

1) Connected the Qt UI to my backend code
2) Finished planet selection
3) Moon mass updated properly with planet selection

connected Qt and backend code for planet type and moon mass

---

src/simulations/fluidSim/CMakeLists.txt
src/simulations/fluidSim/QtApp.cpp
src/simulations/fluidSim/QtApp.hpp
src/simulations/fluidSim/mainFluid.cpp

-  Got Qt working with WSL and vs code
-  Played around with Qt on a separate repo
-  Transferring it to this repo didn't work so I just started a small template

Fluid: Started Qt for the fluid simulation

---

lib/replayTable/replayTableData.cpp
lib/replayTable/replayTableMain.cpp

BUG FIX: fixed error where the table was storing values under the wrong column

Fixed insertion error for the replayTable

---

src/simulations/orbitalMechanics/MainWindow.cpp
src/simulations/orbitalMechanics/orbitSimulation.cpp
src/simulations/orbitalMechanics/orbitSimulation.hpp

1) Finished having the user set initial moon mass, and added helper functions in the backend to do so
2) Added labels for the fields where user will be updating parameters

added more to the Qt UI

---

src/simulations/planeInteraction/CMakeLists.txt
src/simulations/planeInteraction/planeIntMain.cpp

Made adjustments to mainPlane file to interact with QT and updated Cmake.

Updates to Main and Cmakefiles

---

src/simulations/fluidSim/CMakeLists.txt
src/simulations/fluidSim/fluidSim.cpp
src/simulations/fluidSim/mainFluid.cpp
src/simulations/fluidSim/mainQt.cpp
src/simulations/fluidSim/mainWindow.cpp
src/simulations/fluidSim/mainWindow.hpp

-Figured out how to run qt on my machine
-Learned how to use qt creator for GUI design
-Currently only makes a window with a button

Fluid: got qt working

---

src/physics/CMakeLists.txt
src/physics/collisionSystem/CMakeLists.txt
src/physics/collisionSystem/collisionSystem.hpp

adds the beginning of the collision class that will be used to handle all of the collision logic in the sim

feat: start collision class

---

lib/replayTable/replayTable.hpp
lib/replayTable/replayTableData.cpp
lib/replayTable/replayTableMain.cpp

- BUG FIX: Used find function to correctly insert data in exportCSV
- REMOVED: rangeQuery and filter. They are not really worth the effort to implement and don't provide much functionality to replayTable. I may implement this in QT
- TODO: Integrate QT

BUG FIX: Corrected exportCSV, removed rangeQuery and filter functions

---

src/simulations/orbitalMechanics/MainWindow.cpp
src/simulations/orbitalMechanics/MainWindow.hpp
src/simulations/orbitalMechanics/orbitSimulation.cpp
src/simulations/orbitalMechanics/orbitSimulation.hpp
src/simulations/orbitalMechanics/orbitalMechanics.cpp
src/simulations/orbitalMechanics/orbitalMechanics.hpp

1) Added update moon velocity to Qt
2) Added update planet-moon distance to Qt
3) Removed update planet mass entirely (it was causing too much logic trouble with the flow of my coolcam)

finished user interaction with Qt

---

src/simulations/planeInteraction/QtApp.cpp
src/simulations/planeInteraction/QtApp.hpp

Updated the hpp and cpp files so that users can now enter simulation parameters through a simple GUI and see the results in a text area

Updated and expanded on cpp and hpp for QT

---

src/simulations/orbitalMechanics/MainWindow.cpp
src/simulations/orbitalMechanics/orbitalMechanics.cpp
src/simulations/orbitalMechanics/orbitalMechanics.hpp

1) Started working on live 2D position of the moon, so 2D orbital kinematics
-not much code so far, but a lot of time went into thinking of how to do it also finding which equations to use
-more to come

started working on 2D kinematics for orbit

---

lib/replayTable/CMakeLists.txt
lib/replayTable/QtApp.cpp
lib/replayTable/QtApp.hpp
lib/replayTable/QtApp.ui
lib/replayTable/mainQt.cpp
lib/replayTable/replayTable.hpp
lib/replayTable/replayTableData.cpp
lib/replayTable/replayTableMain.cpp

Started implementing my QT Ui.
TODO: Need to allow the user to create a rigidBody for tracking. Right now it has the methods to do so
but does not actually have a rigidBody to track
TODO: Make the UI look good

Began Work on replayTable QT ui

---

.gitignore
src/simulations/lightSim/LightBody.hpp
src/simulations/planetSim/CMakeLists.txt
src/simulations/planetSim/simConfig.cpp
src/simulations/planetSim/simConfig.hpp
src/simulations/planetSim/simulation.cpp
src/simulations/planetSim/simulation.hpp

- implemented the rigid body code into my simulation

implemented rigid body
